### ISSUE TITLE
Will this extension work on Magento 2.0?

### ISSUE THREAD

**Issue by devdesco-ceo** [c3limited/FixerIOCurrencyImport#1]
Will this extension work on Magento 2.0?

**Comment by devdesco-ceo** [comment]
+1

**Comment by mustdobetter** [comment]
Apologies for the late reply. The short answer is that it's unlikely; the extension has not been tested with Magento 2.0. We will be updating all of our extensions to support Magento 2.0 in the near future.

**Comment by inpresif** [comment]
Hi, we get these errors on trying to update. Mage 1.9.2.

Cannot retrieve rate from https://api.fixer.io/latest?base=EUR&symbols=GBP.
Cannot retrieve rate from https://api.fixer.io/latest?base=EUR&symbols=USD.
Cannot retrieve rate from https://api.fixer.io/latest?base=GBP&symbols=EUR.
Cannot retrieve rate from https://api.fixer.io/latest?base=GBP&symbols=USD.
Cannot retrieve rate from https://api.fixer.io/latest?base=USD&symbols=EUR.
Cannot retrieve rate from https://api.fixer.io/latest?base=USD&symbols=GBP.

Is this normal on manual update?

**Comment by maderlock** [comment]
Magento 2 comes with fixer.io functionality built-in :)

**Comment by maderlock** [comment]
@inpresif This is not relevant to this ticket. Please open another if this is still an issue, with more details as to what you are attempting to do.
